services:
  server:
    build: ./server
    container_name: lsc_server
    networks:
      lab_net:
        ipv4_address: 10.10.0.10
    cap_add:
      - NET_ADMIN
    tty: true

  client:
    build: ./client
    container_name: lsc_client
    networks:
      lab_net:
        ipv4_address: 10.10.0.20
    cap_add:
      - NET_ADMIN
    tty: true

  firewall:
    build: ./firewall
    container_name: lsc_firewall
    networks:
      lab_net:
        ipv4_address: 10.10.0.1
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    tty: true

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

