apiVersion: v1
kind: Service
metadata:
  name: node-hello-svc
  namespace: lab-1
spec:
  selector:
    app: node-hello
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
